Main development
axgtz/summer20-sps-team6 pull request #12
Opened 2020-07-18 16:58 UTC by axgtz

2020-07-18 16:59 UTC, the-guti reviewed
We need to standardize import order, as well as the async functions. Also, lets not forget about eof line

2020-07-19 21:28 UTC, astrobliss commented
Could you pull master into this branch and then remake this pull request?

2020-07-19 21:29 UTC, astrobliss requested changes
Can you merge master into this branch and then make another pull request? I'm seeing old changes in this request

2020-07-19 22:10 UTC, astrobliss approved these changes

2020-07-19 22:12 UTC, merged